import type { PatchCategory, PatchState } from '../patch/types'
import { resolveWavetable } from '../wavetables/registry'
import {
  mapPhaseOneVitalParameters,
  setVitalValues,
  VitalExportError,
} from './parameterMap'
import { buildVitalWavetable } from './wavetable'

export interface VitalPresetDocument {
  author?: string
  comments?: string
  preset_name?: string
  preset_style?: string
  synth_version: string
  settings: Record<string, unknown> & { wavetables?: unknown[] }
  [key: string]: unknown
}

export interface VitalExportResult {
  document: VitalPresetDocument
  filename: string
  json: string
}

const CATEGORY_NAMES: Partial<Record<PatchCategory, string>> = {
  pad: 'Pad',
  bass: 'Bass',
  lead: 'Lead',
  pluck: 'Pluck',
  keys: 'Keys',
  atmosphere: 'Atmosphere',
  rhythmic: 'Sequence',
  other: 'Other',
}

function assertVitalDocument(value: unknown): asserts value is VitalPresetDocument {
  if (!value || typeof value !== 'object') throw new VitalExportError('Vital fixture is not an object')
  const document = value as Partial<VitalPresetDocument>
  if (!document.settings || typeof document.settings !== 'object') {
    throw new VitalExportError('Vital fixture has no settings object')
  }
  if (!document.synth_version || typeof document.synth_version !== 'string') {
    throw new VitalExportError('Vital fixture has no pinned synth_version')
  }
  if (!Array.isArray(document.settings.wavetables) || document.settings.wavetables.length < 2) {
    throw new VitalExportError('Vital fixture must contain at least two wavetable slots')
  }
}

export function vitalFilename(name: string): string {
  const safeName = name
    .normalize('NFKD')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()
  return `${safeName || 'wavetable-workbench-patch'}.vital`
}

export class VitalPresetAdapter {
  private readonly template: VitalPresetDocument

  constructor(template: unknown) {
    assertVitalDocument(template)
    this.template = structuredClone(template)
  }

  static async fromUrl(
    url = '/fixtures/vital/init.vital',
    fetchImplementation: typeof fetch = fetch,
  ): Promise<VitalPresetAdapter> {
    const response = await fetchImplementation(url)
    if (!response.ok) {
      throw new VitalExportError(`Unable to load Vital Init fixture (${response.status})`)
    }
    const text = await response.text()
    try {
      return new VitalPresetAdapter(JSON.parse(text))
    } catch (error) {
      if (error instanceof VitalExportError) throw error
      throw new VitalExportError('Vital Init fixture is not valid JSON')
    }
  }

  exportPatch(patch: PatchState): VitalExportResult {
    const output = structuredClone(this.template)
    output.author = 'Wavetable Workbench'
    output.comments = patch.metadata.description ?? 'Generated by Wavetable Workbench'
    output.preset_name = patch.metadata.name
    output.preset_style = patch.metadata.category
      ? CATEGORY_NAMES[patch.metadata.category]
      : 'Other'

    setVitalValues(output.settings, mapPhaseOneVitalParameters(patch))

    const wavetables = output.settings.wavetables as unknown[]
    patch.oscillators.forEach((oscillator, index) => {
      const wavetable = resolveWavetable(patch.wavetableData, oscillator.wavetableId)
      wavetables[index] = buildVitalWavetable(wavetable, output.synth_version)
    })

    const filename = vitalFilename(patch.metadata.name)
    return {
      document: output,
      filename,
      json: JSON.stringify(output),
    }
  }

  downloadPatch(patch: PatchState): string {
    const exported = this.exportPatch(patch)
    const anchor = document.createElement('a')
    anchor.href = URL.createObjectURL(
      new Blob([exported.json], { type: 'application/json;charset=utf-8' }),
    )
    anchor.download = exported.filename
    anchor.click()
    window.setTimeout(() => URL.revokeObjectURL(anchor.href), 4_000)
    return exported.filename
  }
}
